services:
  labby:
    build: .
    container_name: labby
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config:/app/config
    networks:
      - homelab_network
      - docker-proxy-ro
      - docker-proxy-rw
      - homelab_secure
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  homelab_network:
    external: true
  docker-proxy-ro:
    external: true
  docker-proxy-rw:
    external: true
  homelab_secure:
    external: true
