// Curated Lucide set — the single source of truth for which `lucide:<name>` values
// render as an inline glyph. Both Icon.svelte (rendering) and IconPicker.svelte
// (browsing) key off this map, so a name offered in the picker always renders.
import {
  Activity,
  Bell,
  Book,
  Bookmark,
  BookOpen,
  Bot,
  Box,
  Calendar,
  CalendarDays,
  Camera,
  Clapperboard,
  Clock,
  Cloud,
  CloudSun,
  Cpu,
  Database,
  Download,
  Droplet,
  ExternalLink,
  Film,
  Flame,
  Folder,
  FolderOpen,
  Gamepad2,
  Gauge,
  GitBranch,
  Github,
  Globe,
  HardDrive,
  Headphones,
  Heart,
  Home,
  Image,
  Key,
  LayoutDashboard,
  LayoutGrid,
  Link,
  List,
  Lock,
  MapPin,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Music,
  Network,
  Newspaper,
  Package,
  Pause,
  Play,
  Printer,
  Radio,
  Rss,
  Search,
  Server,
  Settings,
  Shield,
  Smartphone,
  Star,
  Sun,
  Terminal,
  Thermometer,
  Tv,
  Upload,
  Users,
  Video,
  Wallet,
  Wifi,
  Wind,
  Zap,
} from 'lucide-svelte';

export const LUCIDE_ICONS: Record<string, typeof Box> = {
  activity: Activity,
  bell: Bell,
  book: Book,
  'book-open': BookOpen,
  bookmark: Bookmark,
  bot: Bot,
  box: Box,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  camera: Camera,
  clapperboard: Clapperboard,
  clock: Clock,
  cloud: Cloud,
  'cloud-sun': CloudSun,
  cpu: Cpu,
  database: Database,
  download: Download,
  droplet: Droplet,
  'external-link': ExternalLink,
  film: Film,
  flame: Flame,
  folder: Folder,
  'folder-open': FolderOpen,
  'gamepad-2': Gamepad2,
  gauge: Gauge,
  'git-branch': GitBranch,
  github: Github,
  globe: Globe,
  'hard-drive': HardDrive,
  headphones: Headphones,
  heart: Heart,
  home: Home,
  image: Image,
  key: Key,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  link: Link,
  list: List,
  lock: Lock,
  'map-pin': MapPin,
  'message-square': MessageSquare,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  music: Music,
  network: Network,
  newspaper: Newspaper,
  package: Package,
  pause: Pause,
  play: Play,
  printer: Printer,
  radio: Radio,
  rss: Rss,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  smartphone: Smartphone,
  star: Star,
  sun: Sun,
  terminal: Terminal,
  thermometer: Thermometer,
  tv: Tv,
  upload: Upload,
  users: Users,
  video: Video,
  wallet: Wallet,
  wifi: Wifi,
  wind: Wind,
  zap: Zap,
};

// Sorted names for the picker grid.
export const LUCIDE_NAMES: string[] = Object.keys(LUCIDE_ICONS).sort();
